/**
Testing throw/catch doesn't mess up PC or VM call stack
*/
var i = 0;
while (i < 3) {
  try {
    throw Error("OMG");
  } catch (Error e) {
    print e.message;
  }
  i = i + 1;
}
__END__
-- expect: --
OMG
OMG
OMG
